services:
  mongo:
    image: mongodb/mongodb-community-server:7.0.16-ubuntu2204
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    
  qdrant:
    image: qdrant/qdrant:v1.12.5
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "qdrant_data:/qdrant_data"
    restart: always

  mq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    restart: always

volumes:
  mongo1_data:
  mongo1_config:
  qdrant_data:
